Added license, copying and notice
rdkcentral/meta-application-development-generic pull request #4
Opened 2024-07-23 16:23 UTC by arun-madhavan-013

2024-07-24 10:24 UTC, mhughesacn requested changes
Hi Arun,
Two comments in LICENSE please.  The reason is that NOTICE is where the copyrights are "real", so if we have e.g. a generic MIT license in the LICENSE file, we can give the credit in NOTICE where there could be several different credits for some MIT code with different years/copyrights.

2024-07-24 10:24 UTC, mhughesacn commented on LICENSE
> +Copyright 2024 RDK Management
Please use the generic
"Copyright [YEAR] [COPYRIGHT HOLDER]"
 here.

2024-07-24 10:24 UTC, mhughesacn commented on LICENSE
> +   Copyright 2024 RDK Management
Please use the generic
"Copyright [YEAR] [COPYRIGHT HOLDER]"
here too.

2024-07-24 16:01 UTC, deepthi-ps approved these changes

2024-07-24 20:09 UTC, deepthi-ps approved these changes

2024-07-29 10:10 UTC, mhughesacn approved these changes

2024-07-29 12:29 UTC, merged